# Generated by Django 5.0.2 on 2024-02-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_userdailyrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdailyrecord',
            old_name='count',
            new_name='post_count',
        ),
    ]
